name: Test and Deploy 

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs:
  Django_test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: docker-compose build
      run: |
        docker-compose build
    - name: docker-compose up
      run: |
        docker-compose up -d
    - name: sleep for launch db to migrate at Django
      run: |
        sleep 10
        docker ps -a
    - name: Grant execute permission of manage.py and Change line feed code
      run: |
        chmod +x ./trannes/manage.py
        vi +':wq ++ff=unix' ./trannes/manage.py
    - name: Django migrate
      run: |
        docker-compose run python ./manage.py migrate
    - name: Django Tests
      run: |
        docker-compose run python ./manage.py test
    - name: docker-compose down
      run: |
        docker-compose down
        
  deploy:
    runs-on: ubuntu-latest
    needs: [Django_test]
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: |
        echo "$SECRET_KEY" > secret_key  
        chmod 600 secret_key
        ssh -i "id_rsa" minecha@ec2-54-150-74-214.ap-northeast-1.compute.amazonaws.com "cd ~/trannes && git pull origin master"
        ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secret_key "cd ~/trannes && git pull origin master"
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      
