name: Test and Deploy 

on:
  push:
    branches: [ master ]

jobs:
  Django_test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: docker-compose build
      run: |
        docker-compose build
    - name: docker-compose up
      run: |
        docker-compose up -d
    - name: sleep for launch db to migrate at Django
      run: |
        sleep 10
        docker ps -a
    - name: Grant execute permission of manage.py and Change line feed code
      run: |
        chmod +x ./trannes/manage.py
        vi +':wq ++ff=unix' ./trannes/manage.py
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev
    - name: Django migrate
      run: |
        docker-compose run python ./manage.py migrate
    - name: Django Tests
      run: |
        docker-compose run python ./manage.py test
    - name: docker-compose down
      run: |
        docker-compose down
        
  deploy:
    runs-on: ubuntu-latest
    needs: [Django_test]
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        echo "$SECRET_KEY" > secretkey
        chmod 600 secretkey
        ssh -o StrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secretkey "cd ~/trannes && git pull origin master"
      
