name: Test and Deploy 

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        echo "$SECRET_KEY" > secretkey
        chmod 600 secretkey
        ssh -oStrictHostKeyChecking=no ${EC2_USER}@${EC2_HOST} -i secretkey "cd ~/trannes && git pull origin master"

